### ISSUE TITLE
1.18.2, crash at game load 

### ISSUE THREAD

**Issue by carlean101** [MennoMax/astikor-carts#87]
When launching the game (1.18.2, mod version 1.1.2), it loads almost completely then crashes and sends me back to the launcher with the error code:

"The game crashed whilst rendering overlay
Error: java.lang.IllegalArgumentException: Failed to create model for minecraft:pig"

This is happening for both me and my friend, sometimes and rarely the game loads but I can't figure out the cause

**Comment by AceTheEldritchKing** [comment]
I've been having the same issue too with the same error message. If I add Astikor carts to any 1.18.2 instance it crashes, with the error being client side.

**Comment by DcNdrew** [comment]
Same bug.

**Comment by Meshinator69** [comment]
I am also having this issue - same error (pig), crashes out.

**Comment by HockeyZman2000** [comment]
Same issue here as well

**Comment by Resulon12** [comment]
Same here also

**Comment by APrimevalWorld** [comment]
Exactly the same problem. They really need to do something about this.

**Comment by SuperStormer** [comment]
Probably fixable by adapting this commit from the TFC fork: https://github.com/Verph/astikor-carts-tfc/commit/4bb4b085b935d85468d0bbd2a616c2aa0c575486

**Comment by xFirefalconx** [comment]
I fixed the issue with Verph's commit info, it's online since yesterday. 
https://www.curseforge.com/minecraft/mc-mods/astikorcarts-horse-carts-pigcrash-fix-fork
I also included the fork root so you can check that I really only fixed the bug issue ;) 
Hope this helps everybody!

**Comment by itsdeadfrosty** [comment]
still not working with 1.18.2 as of current date

which is a shame cause i Adore this mod
